var deck = [
    {type: "card", sprite: "potion", score: -2, title: "Curse of Weakness", desc: "Your victim feels like their life force has somehow drained a bit.", val: 2, effect: "none"},
    {type: "card", sprite: "potion", score: -2, title: "Curse of Weakness", desc: "Your victim feels like their life force has somehow drained a bit.", val: 2, effect: "none"},
    {type: "card", sprite: "potion", score: -2, title: "Curse of Weakness", desc: "Your victim feels like their life force has somehow drained a bit.", val: 2, effect: "none"},
    {type: "card", sprite: "potion", score: -2, title: "Curse of Weakness", desc: "Your victim feels like their life force has somehow drained a bit.", val: 2, effect: "none"},
    {type: "card", sprite: "potion", score: -2, title: "Curse of Weakness", desc: "Your victim feels like their life force has somehow drained a bit.", val: 2, effect: "none"},
    {type: "card", sprite: "potion", score: -2, title: "Curse of Weakness", desc: "Your victim feels like their life force has somehow drained a bit.", val: 2, effect: "none"},
    {type: "card", sprite: "potion", score: -2, title: "Curse of Weakness", desc: "Your victim feels like their life force has somehow drained a bit.", val: 2, effect: "none"},
    {type: "card", sprite: "potion", score: -2, title: "Curse of Weakness", desc: "Your victim feels like their life force has somehow drained a bit.", val: 2, effect: "none"},
    {type: "card", sprite: "potion", score: -2, title: "Curse of Weakness", desc: "Your victim feels like their life force has somehow drained a bit.", val: 2, effect: "none"},
    {type: "card", sprite: "potion", score: -2, title: "Curse of Weakness", desc: "Your victim feels like their life force has somehow drained a bit.", val: 2, effect: "none"},
    {type: "card", sprite: "potion", score: -2, title: "Curse of Weakness", desc: "Your victim feels like their life force has somehow drained a bit.", val: 2, effect: "none"},
    {type: "card", sprite: "potion", score: -2, title: "Curse of Weakness", desc: "Your victim feels like their life force has somehow drained a bit.", val: 2, effect: "none"},
    {type: "card", sprite: "potion", score: -2, title: "Curse of Weakness", desc: "Your victim feels like their life force has somehow drained a bit.", val: 2, effect: "none"},
    {type: "card", sprite: "potion", score: -2, title: "Curse of Weakness", desc: "Your victim feels like their life force has somehow drained a bit.", val: 2, effect: "none"},
    {type: "card", sprite: "potion", score: -2, title: "Curse of Weakness", desc: "Your victim feels like their life force has somehow drained a bit.", val: 2, effect: "none"},
    {type: "card", sprite: "potion", score: -2, title: "Curse of Weakness", desc: "Your victim feels like their life force has somehow drained a bit.", val: 2, effect: "none"},
    {type: "item", sprite: "bone-sword", score: 4, title: "Bone Sword of Victory", desc: "... That's pretty gross, actually.", val: 4, effect: "none"},
    {type: "item", sprite: "bone-sword", score: 4, title: "Bone Sword of Victory", desc: "... That's pretty gross, actually.", val: 4, effect: "none"},
    {type: "item", sprite: "bone-sword", score: 4, title: "Bone Sword of Victory", desc: "... That's pretty gross, actually.", val: 4, effect: "none"},
    {type: "item", sprite: "bone-sword", score: 4, title: "Bone Sword of Victory", desc: "... That's pretty gross, actually.", val: 4, effect: "none"},
    {type: "item", sprite: "bone-sword", score: 4, title: "Bone Sword of Victory", desc: "... That's pretty gross, actually.", val: 4, effect: "none"},
    {type: "item", sprite: "bone-sword", score: 4, title: "Bone Sword of Victory", desc: "... That's pretty gross, actually.", val: 4, effect: "none"},
    {type: "item", sprite: "bone-sword", score: 4, title: "Bone Sword of Victory", desc: "... That's pretty gross, actually.", val: 4, effect: "none"},
    {type: "item", sprite: "bone-sword", score: 4, title: "Bone Sword of Victory", desc: "... That's pretty gross, actually.", val: 4, effect: "none"},
    {type: "item", sprite: "bone-sword", score: 4, title: "Bone Sword of Victory", desc: "... That's pretty gross, actually.", val: 4, effect: "none"},
    {type: "item", sprite: "bone-sword", score: 4, title: "Bone Sword of Victory", desc: "... That's pretty gross, actually.", val: 4, effect: "none"},
    {type: "item", sprite: "bone-sword", score: 4, title: "Bone Sword of Victory", desc: "... That's pretty gross, actually.", val: 4, effect: "none"},
    {type: "item", sprite: "bone-sword", score: 4, title: "Bone Sword of Victory", desc: "... That's pretty gross, actually.", val: 4, effect: "none"},
    {type: "item", sprite: "bone-sword", score: 4, title: "Bone Sword of Victory", desc: "... That's pretty gross, actually.", val: 4, effect: "none"},
    {type: "item", sprite: "bone-sword", score: 4, title: "Bone Sword of Victory", desc: "... That's pretty gross, actually.", val: 4, effect: "none"},
    {type: "item", sprite: "bone-sword", score: 4, title: "Bone Sword of Victory", desc: "... That's pretty gross, actually.", val: 4, effect: "none"},
    {type: "item", sprite: "bone-sword", score: 4, title: "Bone Sword of Victory", desc: "... That's pretty gross, actually.", val: 4, effect: "none"}
];
